name: Test 24.04

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-24.04
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: 'temurin'
            -   name: Cache Maven Repository
                uses: actions/cache@v4.1.2
                with:
                    path: ~/.m2/repository
                    key: maven-test-${{ hashFiles('pom.xml') }}
            -   name: Maven test
                run: |
                    java -version
                    mvn clean test
